### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by Runner85sx** [DEV-MSM8909/android_device_huawei_yax_lte#2]
Please describe what you did and what you like to do.

I always need to restart lunch cm_y6_lte-userdebug && make -j6

to finish the build.

Otherwise i would get an error.

Device: Huawei y6, msm8909 Kernel

**Comment by CarlosArriagaCM** [comment]
. build/envsetup and brunch device_codename

**Comment by Runner85sx** [comment]
a fresh "repo init" ....... and so on gives the following:

build/core/binary.mk:745: Das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/obj/STATIC_LIBRARIES/libc_bionic_intermediates/arch-arm/bionic/memcmp.o“ steht mehrfach in derselben Regel.
find: "dummy": Datei oder Verzeichnis nicht gefunden
find: "../../../../../../external/hamcrest/src": Datei oder Verzeichnis nicht gefunden
find: "../../../../../../external/junit/src/org": Datei oder Verzeichnis nicht gefunden
find: "../../../../../../external/hamcrest/src": Datei oder Verzeichnis nicht gefunden
build/core/copy_headers.mk:15: Warnung: Die Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/obj/include/qcom/display/copybit.h“ werden überschrieben
build/core/copy_headers.mk:15: Warnung: Alte Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/obj/include/qcom/display/copybit.h“ werden ignoriert
build/core/copy_headers.mk:15: Warnung: Die Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/obj/include/qcom/display/copybit_priv.h“ werden überschrieben
build/core/copy_headers.mk:15: Warnung: Alte Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/obj/include/qcom/display/copybit_priv.h“ werden ignoriert
build/core/copy_headers.mk:15: Warnung: Die Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/obj/include/qcom/display/c2d2.h“ werden überschrieben
build/core/copy_headers.mk:15: Warnung: Alte Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/obj/include/qcom/display/c2d2.h“ werden ignoriert
build/core/Makefile:46: Warnung: Die Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/system/bin/rild“ werden überschrieben
build/core/base_rules.mk:550: Warnung: Alte Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/system/bin/rild“ werden ignoriert
build/core/Makefile:46: Warnung: Die Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/system/lib/libril.so“ werden überschrieben
build/core/base_rules.mk:550: Warnung: Alte Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/system/lib/libril.so“ werden ignoriert
build/core/Makefile:46: Warnung: Die Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/system/etc/wifi/wpa_supplicant.conf“ werden überschrieben
build/core/base_rules.mk:550: Warnung: Alte Befehle für das Ziel „/home/matze/cm12-1/out/target/product/yax_lte/system/etc/wifi/wpa_supplicant.conf“ werden ignoriert
No private recovery resources for TARGET_DEVICE yax_lte
target StaticExecutable: minivold (/home/matze/cm12-1/out/target/product/yax_lte/obj/RECOVERY_EXECUTABLES/minivold_intermediates/LINKED/minivold)
target StaticExecutable: recovery_e2fsck (/home/matze/cm12-1/out/target/product/yax_lte/obj/RECOVERY_EXECUTABLES/recovery_e2fsck_intermediates/LINKED/e2fsck)
target StaticExecutable: recovery_mke2fs (/home/matze/cm12-1/out/target/product/yax_lte/obj/RECOVERY_EXECUTABLES/recovery_mke2fs_intermediates/LINKED/mke2fs)
target StaticExecutable: recovery_tune2fs (/home/matze/cm12-1/out/target/product/yax_lte/obj/RECOVERY_EXECUTABLES/recovery_tune2fs_intermediates/LINKED/tune2fs)
Symlink: /home/matze/cm12-1/out/target/product/yax_lte/recovery/root/sbin/fsck.exfat -> mount.exfat
Symlink: /home/matze/cm12-1/out/target/product/yax_lte/recovery/root/sbin/mkfs.exfat -> mount.exfat
target StaticExecutable: bu_recovery (/home/matze/cm12-1/out/target/product/yax_lte/obj/RECOVERY_EXECUTABLES/bu_recovery_intermediates/LINKED/bu)
Symlink: /home/matze/cm12-1/out/target/product/yax_lte/recovery/root/sbin/busybox -> recovery
Symlink: /home/matze/cm12-1/out/target/product/yax_lte/recovery/root/sbin/getprop -> recovery
Symlink: /home/matze/cm12-1/out/target/product/yax_lte/recovery/root/sbin/make_ext4fs -> recovery
Symlink: /home/matze/cm12-1/out/target/product/yax_lte/recovery/root/sbin/minizip -> recovery
/home/matze/cm12-1/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.8/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /home/matze/cm12-1/out/target/product/yax_lte/obj/STATIC_LIBRARIES/libstlport_static_intermediates/libstlport_static.a: file is empty
external/stlport/stlport/stl/_alloc.h:158: error: undefined reference to 'std::__node_alloc::_M_allocate(unsigned int&)'
external/stlport/stlport/stl/_alloc.h:161: error: undefined reference to 'std::__node_alloc::_M_deallocate(void*, unsigned int)'
external/stlport/stlport/stl/_string.c:600: error: undefined reference to 'std::__stl_throw_length_error(char const*)'
collect2: error: ld returned 1 exit status
build/core/executable_internal.mk:66: die Regel für Ziel „/home/matze/cm12-1/out/target/product/yax_lte/obj/RECOVERY_EXECUTABLES/minivold_intermediates/LINKED/minivold“ scheiterte
make: *** [/home/matze/cm12-1/out/target/product/yax_lte/obj/RECOVERY_EXECUTABLES/minivold_intermediates/LINKED/minivold] Fehler 1
make: *** Auf noch nicht beendete Prozesse wird gewartet …
Symlink: /home/matze/cm12-1/out/target/product/yax_lte/recovery/root/sbin/reboot -> recovery
make: Verzeichnis „/home/matze/cm12-1“ wird verlassen

#### make failed to build some targets (01:54 (mm:ss)) ####

**Comment by Runner85sx** [comment]
i used: brunch cm_yax_lte-userdebug

**Comment by Runner85sx** [comment]
Fresh Compile:

matze@BuildBox:~/cm12-1$ source build/envsetup.sh
including device/generic/mini-emulator-arm64/vendorsetup.sh
including device/generic/mini-emulator-mips/vendorsetup.sh
including device/generic/mini-emulator-x86/vendorsetup.sh
including device/generic/mini-emulator-x86_64/vendorsetup.sh
including device/generic/mini-emulator-armv7-a-neon/vendorsetup.sh
including device/huawei/yax_lte/vendorsetup.sh
including vendor/cm/vendorsetup.sh
including sdk/bash_completion/adb.bash
including vendor/cm/bash_completion/git.bash
including vendor/cm/bash_completion/repo.bash
matze@BuildBox:~/cm12-1$ brunch cm_yax_lte-eng
including vendor/cm/vendorsetup.sh
Trying dependencies-only mode on a non-existing device tree?

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=5.1.1
CM_VERSION=12.1-20160619-UNOFFICIAL-yax_lte
TARGET_PRODUCT=cm_yax_lte
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=cortex-a7
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.4.0-24-generic-x86_64-with-Ubuntu-16.04-xenial
HOST_BUILD_TYPE=release
BUILD_ID=LMY49J
OUT_DIR=/home/matze/cm12-1/out
============================================

make: Verzeichnis „/home/matze/cm12-1“ wird betreten
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=5.1.1
CM_VERSION=12.1-20160619-UNOFFICIAL-yax_lte
TARGET_PRODUCT=cm_yax_lte
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=cortex-a7
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.4.0-24-generic-x86_64-with-Ubuntu-16.04-xenial
HOST_BUILD_TYPE=release
BUILD_ID=LMY49J
OUT_DIR=/home/matze/cm12-1/out
============================================
